Fix: corrected TypeError in time calculations
Fatal error: Uncaught TypeError: Unsupported operand types: string / int in C:\ibtchub.local\www\system\functions\ftime.php:100 Stack trace:
#0 C:\ibtchub.local\www\panel\desktop\plugins\speed.php(41): stime('1725523208')
#1 C:\ibtchub.local\www\panel\desktop\index.php(23): require('C:\\ibtchub.loca...')
#2 C:\ibtchub.local\www\system\connections\controller.php(55): require_once('C:\\ibtchub.loca...')
#3 C:\ibtchub.local\www\index.php(4): require_once('C:\\ibtchub.loca...')
#4 {main} thrown in C:\ibtchub.local\www\system\functions\ftime.php on line 100